spring:
  application:
    name: ms-customer

server:
  port: 8600

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/

keycloak:
  auth-server-url: http://localhost:8180/auth
  autodetect-bearer-only: true
  resource: cirrus
  credentials:
    secret: pBNzZnKTkDZnJuZPqjqmc4OdJJuExr0z
  realm: senasir
  securityConstraints:
    - authRoles:
        - ADMIN
      securityCollections:
        - name: REST API ADMIN
          patterns:
            - /v1/api/customer
    - securityCollections:
        - patterns:
            - /v1/api/customer/test